exports.loginUser = 'div.caiui-input-text-wrap.width-normal.height-normal input[type="text"]'
exports.loginPassword = 'div.caiui-input-text-wrap.width-normal.height-normal input[type="password"]'
exports.loginSubmit = 'button.cai-button.submit-button'
exports.adminIn = '#cps-container > main > div > ul:nth-child(1) > li:nth-child(2)'
exports.chooseAdmin = '#cps-container > main > div > ul:nth-child(3) > li > button'